### PR TITLE
Added 4 new codes

### PR DESCRIPTION
**Pull request by urstrulykkr**
*Codes for Tuple, Dictionary, list & get() method for dictionaries.
*The Tuple code can be revamped. 
what say @aravindvnair99

### CODE REVIEW

**Comment by urstrulykkr** [comment]
Hope you like it @aravindvnair99

**Comment by urstrulykkr** [comment]
Is our chat encrypted? :speak_no_evil:

**Comment by aravindvnair99** [comment]
@urstrulykkr Any updates?

**Comment by aravindvnair99** [comment]
@urstrulykkr Inactivity alert. ⚠️ PR will be auto closed if there's no response in a week's time.

**Comment by urstrulykkr** [comment]
Pardon me. Aravi, I would soon look on it .

**Comment by aravindvnair99** [comment]
@urstrulykkr Closing pull request due to 3 months of inactivity. Please make a new pull request with updated code to resume the merge process.

**Pull request closed without merging**
